travis:
  secure:
    BINSTAR_TOKEN: kzBy4TFiV2+sM75j95sZWOwXl+Jj3e9oFE+3vWHN+rfwzGTgMn4MjvQh/KCmobvoNch7gytST3ri8AY4GcfuDq1YHgpxphhuHtKWz37NNT3UzcRCAExHeCuwjUav3JGKHYq9qUIElpgNbDou5OKHZzxKMzsexMdSL6LHpdroZZ4/CmuPboWRRqshzvNI6jMaMviWRwF9s648/9NzLWWL6GPM6Fdqi8UbghdHNxq9YKtHiY7jOWkj8ClQPDQGS0b8AeQuLsU/7ielcZiIrxZa8EPp5ifF2Qfzmc7QiyLNsi/BY4nw9PxpREJJDh6VtpSiZ2lQ7Ha4tCqRFNxlcHbj7CWc92JV3wFxZHge3HdxupqYnVzSV/fXplePMuEJcRJ9qpgLFu5kAfaaKo8PLOVh9QWVVqtevEbfkuNMMO10eQ7BXE9Nz3Ifw2oYdg5TIvxCUEIXPmMcPu77Jl4VQ7RsXAIxQtizJNXxEa0d/32rdveQkg9RZ7RlmcnG3vIFkAP1U1D26ekeOjtrk6WhSFLXHeXsSWRBY3AjSEtB5/P2CTFlBfmdoqRkWuCDpw35kneKUl4kvyIHHyxKCPJnU541EdtkAamqoQPTnX8mwMQF6rgyoycbu7U2OHZSXfltFK2m2n0ypzbzW88QZ1au3I7+GH1Z3CLcYLWBad6LrDpiuoo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
